POST http://localhost:3000/mangas
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6Im1hcmNvcyIsIm5vbWJyZVVzdWFyaW8iOiJmcm9udXgiLCJtYW5nYXMiOltdLCJpZCI6IjY2M2Y5MjVhMmZlYzdkNGQ0ZmYzOTc2MCJ9LCJpYXQiOjE3MTU0NDIyNzEsImV4cCI6MTcxNTQ0NTg3MX0.qE4rG9ksBdjUnIwJfZNJ2ClhUNPQ883NJu3zJxNgPa8


{    
    "titulo": "Naruto",
    "estado": "Siguiendo"
}