POST http://localhost:3000/mangas
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6Im1hcmNvcyIsIm5vbWJyZVVzdWFyaW8iOiJmcm9udXgiLCJtYW5nYXMiOlsiNjYzZjkyNzgyZmVjN2Q0ZDRmZjM5NzY0IiwiNjY0MjdiZjUwYjU1ZGJiZWQwNGQ5ZjFlIiwiNjY0MjdjZDgwYjU1ZGJiZWQwNGQ5ZjIyIiwiNjY0MjdjZTIwYjU1ZGJiZWQwNGQ5ZjI2IiwiNjY0MjdjZTgwYjU1ZGJiZWQwNGQ5ZjJhIiwiNjY0MmUzOWYwMjA0MDI0NGQ5NDkxODM3IiwiNjY0NjQxYjU1ZDZlNGY4MGQ1MTVhYTY5IiwiNjY0NjQzMzRjY2QzNjIxMDNmNmU2MzI0IiwiNjY0NjQzNDFjY2QzNjIxMDNmNmU2MzJjIiwiNjY0NjQ2MzI5NTZkZThkNTJmZjllMjllIl0sImlkIjoiNjYzZjkyNWEyZmVjN2Q0ZDRmZjM5NzYwIn0sImlhdCI6MTcxNTg5MDM3NiwiZXhwIjoxNzE1ODkzOTc2fQ.omq36DqLEIP-8ae-bXjvcsR2FUe6akfSjKddQSdSNdU

{    
    "titulo": "Evangelion",
    "estado": "Siguiendo",
    "tipo": "Manga",
    "genero": ["66464624956de8d52ff9e29b", "6646683d956de8d52ff9e2a3"]
}