POST http://localhost:3000/mangas
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6Im1hcmNvcyIsIm5vbWJyZVVzdWFyaW8iOiJmcm9udXgiLCJtYW5nYXMiOlsiNjYzZTk3YmViY2ZmMGVhYWJkMmMwOWY3Il0sImNhcGl0dWxvcyI6W10sImlkIjoiNjYzZTk3NDdiY2ZmMGVhYWJkMmMwOWYxIn0sImlhdCI6MTcxNTM4MjEyMiwiZXhwIjoxNzE1Mzg1NzIyfQ.f8uffBsisau59JxgaEFWLKDKFMoO_zu3L-xl-IPhrck

{    
    "titulo": "Naruto3",
    "estado": "Siguiendo",
    "usuario": "663e9758bcff0eaabd2c09f3"
}