POST http://localhost:4000/capitulos
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7Im5vbWJyZSI6Im1hcmNvcyIsIm5vbWJyZVVzdWFyaW8iOiJmcm9udXgiLCJtYW5nYXMiOlsiNjYzZjkyNzgyZmVjN2Q0ZDRmZjM5NzY0IiwiNjY0MjdiZjUwYjU1ZGJiZWQwNGQ5ZjFlIiwiNjY0MjdjZDgwYjU1ZGJiZWQwNGQ5ZjIyIiwiNjY0MjdjZTIwYjU1ZGJiZWQwNGQ5ZjI2IiwiNjY0MjdjZTgwYjU1ZGJiZWQwNGQ5ZjJhIl0sImlkIjoiNjYzZjkyNWEyZmVjN2Q0ZDRmZjM5NzYwIn0sImlhdCI6MTcxNTY1OTAyMCwiZXhwIjoxNzE1NjYyNjIwfQ.cncleubI1lje2pQ_UPY7wxBzjpqGv3dZJPiCq1tCMZk

{    
    "numero": 21,
    "imagenes": ["dd","ff","ññ","lala","lelele","jejeje"],
    "siguiendo": true,
    "mangas": "66427ce80b55dbbed04d9f2a"
}